### PR TITLE
adding changes to ui for advanced search

### LINKED ISSUE #22: Advanced search UI changes
Frontend for https://github.com/YangCatalog/backend/pull/721.

Searching with the advanced search tab selected needs to use the new `/advanced-search` endpoint.
Requests to this endpoint have the following format:
```
{
    "include-mibs": <bool>,
    "latest-revision": <bool>,
    "yang-versions": <list of strings>,
    "schema-types": <list of strings>,
    "output_columns": <list of strings>,
    "include-drafts": <bool>,
    "sub-search": {
        "name": {"string": <string>, "must": <bool>, "regex": <bool>},
        "revision": {"string": <string>, "must": <bool>},
        "path": {"string": <string>, "must": <bool>},
        "module": {"string": <string>, "must": <bool>, "regex": <bool>},
        "organization": {"string": <string>, "must": <bool>},
        "maturity": {"string": <string>, "must": <bool>},
        "description": {"string": <string>, "must": <bool>, "case_insensitive": <bool>, "use_synonyms": <bool>, "regex": <bool>}
    }
}
```
The fields inside `sub-search` are optional, but at least one must be present.
`must` signifies whether the sub search must match all search results.

The UI could look similar to how it is now, with the correct set of checkboxes added for each type of sub search.

### PR DESCRIPTION
**Pull request by dmytro-kyrychenko**

### CODE REVIEW

**Comment by richardzilincikPantheon** [comment]
I'll try and get this running locally to have a look at it, but could you also please add some screenshots here?

**Comment by dmytro-kyrychenko** [comment]
sure

this is how it looks for simple search (basically same as before)
image

**Comment by dmytro-kyrychenko** [comment]
and this is the look of advanced tab

image

**Review by richardzilincikPantheon — CHANGES_REQUESTED** [review]
Description subsearch is missing checkboxes for `case_insensitive` and `use_synonyms`.

When removing a subsearch, if it isn't the last one on the list, the type of the deleted subsearch replaces the type of the subsearch that was previously bellow it (for example set the first one to "foo" and "module-name", set the second one to "bar" and revision, remove the first one).

**Comment by dmytro-kyrychenko** [comment]
Actually, we have checkboxes for case_insensitive and use_synonyms, but they are on the original tab, not the advanced search one, so I understand that this must be not user friendly, so I'll add them separately to advanced tab

**Comment by richardzilincikPantheon** [comment]
> Actually, we have checkboxes for case_insensitive and use_synonyms, but they are on the original tab, not the advanced search one, so I understand that this must be not user friendly, so I'll add them separately to advanced tab

Oh right, I didn't realize that. But yes, it would probably be better to add them here too.

**Review by richardzilincikPantheon — APPROVED** [review]

**Review by SlavomirMazurPantheon — APPROVED** [review]

**Pull request merged**
